spring:
  application:
    name: distributed-transactions-api
  liquibase:
    enabled: true

datasource:
  central-db:
    jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=CentralDB;encrypt=true;trustServerCertificate=true;
    username: central_login
    password: Central_password1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    liquibase:
      change-log: db/changelog/db.central.changelog-master.yml
  branches:
    first-branch-db:
      url: jdbc:sqlserver://localhost:1433;databaseName=FirstBranchDB;encrypt=true;trustServerCertificate=true;
      username: first_branch_login
      password: First_branch_password1
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    second-branch-db:
      url: jdbc:sqlserver://localhost:1433;databaseName=SecondBranchDB;encrypt=true;trustServerCertificate=true;
      username: second_branch_login
      password: Second_branch_password1
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    third-branch-db:
      url: jdbc:sqlserver://localhost:1433;databaseName=ThirdBranchDB;encrypt=true;trustServerCertificate=true;
      username: third_branch_login
      password: Third_branch_password1
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    liquibase:
      change-log: db/changelog/db.branch.changelog-master.yml